name: CI Pipeline For Wordpress Application

on:
  push:

jobs:
  getTimeStamp:
    runs-on: ubuntu-latest
    environment: "Development"
    steps:
      - name: Get the current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
        shell: bash
  console:
    runs-on: ubuntu-latest
    environment: "Development"
    steps:
      - name: Get the current date
        id: date
        run: echo "timeStamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Check out code
        uses: actions/checkout@v2
      # - name: Find and Replace
      #   uses: flcdrg/replace-multiple-action@v1
      #   with:
      #     files: './*/*/*/*.yml'
      #     find: '[{ "find": "test", "replace": "hello" }]'

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "test"
          replace: "world${{env.timeStamp}}"
          include: "***.yml" # Will match all README.md files in any nested directory
      - uses: actions/checkout@v2 
      - name: Print File Contents
        run: |
          # Use the find command to locate and print the contents of the .md files
          find . -name '*.yml' -type f -print0 | xargs -0 -I {} sh -c 'echo "Contents of {}:"; cat "{}"; echo "";'

#   Deploy:
#     runs-on: ubuntu-latest
    
#     steps:
#       - uses: actions/checkout@v2 
#       - name: Deploy in EC2
#         env:
#             PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
#             HOSTNAME : ${{ secrets.HOSTNAME  }}
#             USER_NAME : ${{ secrets.USER_NAME  }}
            
#         run: |
#           echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
#           ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
#           echo ***SUCCESSFULLY CONNECTED***
#           cd wordpress
#           ls
#           wordpressfile=$(ls)
#           echo wp-content file: ${wordpressfile}
#           '
#           localPath=$(ls)
#           echo local file: ${localPath}
#           sudo scp -o StrictHostKeyChecking=no -i private_key README.md ${USER_NAME}@${HOSTNAME}:wordpress
#           echo ****FILE TRANSFERED SUCCESSFULLY****

            
