name: CI Pipeline For Wordpress Application

on:
  push:

jobs:
  getTimeStamp:
    runs-on: ubuntu-latest
    environment: "Development"
    steps:
      - name: Get the current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
        shell: bash
  console:
    needs: 
      - getTimeStamp
    runs-on: ubuntu-latest
    environment: "Development"
    steps:

      - uses: flcdrg/replace-multiple-action@v1
        with:
          files: './*.md'
          find: '[{ "find": "EC2-CI-CD", "replace": "abcMany" }]'
      - name: Print File Contents
        run: |
          # Use a loop to print the contents of the .md files
          for file in ./*.md; do
            echo "Contents of $file:"
            cat "$file"
            echo "" # Add a new line between files for better readability
          done

#   Deploy:
#     runs-on: ubuntu-latest
    
#     steps:
#       - uses: actions/checkout@v2 
#       - name: Deploy in EC2
#         env:
#             PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
#             HOSTNAME : ${{ secrets.HOSTNAME  }}
#             USER_NAME : ${{ secrets.USER_NAME  }}
            
#         run: |
#           echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
#           ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
#           echo ***SUCCESSFULLY CONNECTED***
#           cd wordpress
#           ls
#           wordpressfile=$(ls)
#           echo wp-content file: ${wordpressfile}
#           '
#           localPath=$(ls)
#           echo local file: ${localPath}
#           sudo scp -o StrictHostKeyChecking=no -i private_key README.md ${USER_NAME}@${HOSTNAME}:wordpress
#           echo ****FILE TRANSFERED SUCCESSFULLY****

            
