name: CI Pipeline For Wordpress Application

on:
  push:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            
        run: |

          ssh -o StrictHostKeyChecking=no -i PRIVATE_KEY ${USER_NAME}@${HOSTNAME} '
          echo ***SUCCESSFULLY CONNECTED***
          sudo chmod u+w wordpress
          ls -l wordpress
          cd wordpress
          ls
          wordpressfile=$(ls)
          echo wp-content file: ${wordpressfile}
          cd wp-content
          wpcontent=$(ls)
          echo wp-content file: ${wpcontent}
          '
          localPath=$(ls)
          echo local file: ${localPath}

            