name: CI Pipeline For Wordpress Application

on:
  push:

jobs:
         
  Deploy:
    runs-on: ubuntu-latest
    env:
      region: ${{ inputs.region }}
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2 
        run: |
          echo ${{ env.region }}
