name: SAM Api Development (CI) Pipeline

on:
  push:
    branches:
      - 'release/**'  # Triggers on any branch that starts with 'release/'
  release:
    types:
      - published  # Trigger when a release is published

jobs:
  CibtPayApi:
    strategy:
      matrix:
        region: ['us-east-1', 'eu-central-1']
    uses: vignesh1424/EC2-CI-CD/.github/workflows/test.yml@main
    with:
      region: ${{ matrix.region }}
