name: CI Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Specify the environment'
        required: false
        default: ''

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'Development' }}
    steps:
      - name: Set Environment Variable
        run: echo "ENVIRONMENT=${{ secrets.ENVIRONMENT_VARIABLE || 'Development' }}" >> $GITHUB_ENV

      - name: Check Environment
        run: echo "Environment=${{ inputs.environment }}"
